#!/bin/sh
echo "                   GITHUB INSTALLER SCRIPT GO THREW AND "
echo "                                  UNCOMMENT             "
echo "                            BEFORE RUNNING GHUBB        "
sleep 3
clear
#...............................................................TOOL-X

#  git clone https://github.com/rajkumardusad/Tool-X

#...............................................................DarkFly

#  git clone https://github.com/Ranginang67/DarkFly-Tool

#...............................................................NICK BRIGGS REPO

#  git clone https://github.com/nickbriggs501/master 

#...............................................................D8m0ns REPO

#  git clone https://github.com/D8m0n/zsh

#.................................................................ZSH-SYNTAX

#  git clone https://github.com/zsh-users/zsh-syntax-highlighting

#  echo "source /$HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh" >> .zshrc

#  echo "source /$HOME/zsh/alias.txt" >> .zshrc

#.................................................................IP-TRACER

#  git clone https://github.com/rajkumardusad/IP-Tracer

Source $HONE/zsh/tools
